apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-examples
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertx-examples
  template:
    metadata:
      labels:
        app: vertx-examples
    spec:
      securityContext:
            runAsUser: 0
      containers:
        - name: vertx-examples
          image: mohamedfazil/vertx-examples:main-7a2da3a
          # command: ["/bin/sleep", "3650d"]
          ports:
          - name: httpport
            containerPort: 8080
          
